### ISSUE TITLE
404

### ISSUE THREAD

**Issue by LOGOLEX** [nefiertsrebliS/MQTTworx#1]
Hallo,
meine Bridge verbindet sich seit geraumer Zeit nicht mehr mit dem Worx Server

Log:
`root@NLW2:/home/alex/mqtt-landroid-bridge/log# cat mqtt-landroid-bridge.log
Thu, 18 May 2023 20:40:02 GMT INFO: worx is selected
Thu, 18 May 2023 20:40:02 GMT INFO: Topic robi sucessfully connected with local MQTT-Server
Thu, 18 May 2023 20:40:02 GMT ERROR: Could not Connect to Worx Server: StatusCodeError: 404 - {"message":"Not Found","code":"404.000"}
Thu, 18 May 2023 20:40:02 GMT ERROR: StatusCodeError: 404 - {"message":"Not Found","code":"404.000"}`

(In IPS sind Bridge und Roboter als offline gekennzeichnet)

woran könnte das liegen?

**Comment by nefiertsrebliS** [comment]
Offensichtlich hast du lange kein Update mehr gemacht. Gehe mal auf den neuesten Stand der Bridge.

**Comment by LOGOLEX** [comment]
Stimmt, das hab ich nachgeholt, danke!

Die Bridge hat nach dem Update allerdings beim starten irgendwas mit Nodejs gemeckert und dann immer noch den Dienst verweigert.
Nodejs ist jetzt auf 18.X (Letzte Stable)

Und siehe da: läuft wieder.

Leider nur für einige Stunden, dann stoppt der Service

`
> service mqtt-landroid-bridge status
● mqtt-landroid-bridge.service - LSB: start and stop node
     Loaded: loaded (/etc/init.d/mqtt-landroid-bridge; generated)
     Active: active (exited) since Sat 2023-05-20 19:49:16 CEST; 5 days ago
       Docs: man:systemd-sysv-generator(8)
    Process: 1046486 ExecStart=/etc/init.d/mqtt-landroid-bridge start (code=exited, status=0/SUCCESS)
Mai 20 19:49:16 NLW2 systemd[1]: Starting LSB: start and stop node...
Mai 20 19:49:16 NLW2 mqtt-landroid-bridge[1046486]: mqtt-landroid-bridge stopped, but pid file exists
Mai 20 19:49:16 NLW2 mqtt-landroid-bridge[1046486]: Forcing start anyways
Mai 20 19:49:16 NLW2 mqtt-landroid-bridge[1046486]: Removing pid file
Mai 20 19:49:16 NLW2 mqtt-landroid-bridge[1046486]: Starting mqtt-landroid-bridge ...
Mai 20 19:49:16 NLW2 sudo[1046496]:     root : TTY=unknown ; PWD=/ ; USER=alex ; COMMAND=/bin/bash
Mai 20 19:49:16 NLW2 sudo[1046496]: pam_unix(sudo:session): session opened for user alex by (uid=0)
Mai 20 19:49:16 NLW2 sudo[1046496]: pam_unix(sudo:session): session closed for user alex
Mai 20 19:49:16 NLW2 mqtt-landroid-bridge[1046486]: mqtt-landroid-bridge started with pid 1046502
Mai 20 19:49:16 NLW2 systemd[1]: Started LSB: start and stop node.`

Ist das ein neues Thema wert oder kannst Du mir da auf die schnelle was zu sagen?

**Comment by nefiertsrebliS** [comment]
Ich sehe in deinem Status keinerlei Fehler. Die Bridge ist nur nicht aktiv.
Bitte bei weiterem Supportbedarf, im Symcon-Forum anfragen.
